import { GlobalLoader } from '@/components/GlobalLoader'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/assets/css/global.scss'
import { Suspense } from 'react'
import { Nav } from '@/components/Nav'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextJS Movies',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalLoader />
        <Nav />
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  )
}
